### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by arshpreetsingh** [mradway/hycohanz#121]
when I try to connect with Anasys hfss student version I get the following error, Can you pass me through?

> > > [oAnsoftApp, oDesktop] = hfss.setup_interface()
> > > Traceback (most recent call last):
> > >   File "<interactive input>", line 1, in <module>
> > >   File "C:\Python27\lib\site-packages\hycohanz\appobject.py", line 34, in setup_interface
> > >     oAnsoftApp = win32com.client.Dispatch('AnsoftHfss.HfssScriptInterface')
> > >   File "C:\Python27\lib\site-packages\win32com\client__init__.py", line 95, in Dispatch
> > >     dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
> > >   File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 108, in _GetGoodDispatchAndUserName
> > >     return (_GetGoodDispatch(IDispatch, clsctx), userName)
> > >   File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 85, in _GetGoodDispatch
> > >     IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
> > > com_error: (-2147221005, 'Invalid class string', None, None)

**Comment by mradway** [comment]
Sorry for the delayed reply, and thanks for the question. I haven't seen this behavior before.  Can you send a numerical version number from the About window so I can attempt to replicate?

**Comment by arshpreetsingh** [comment]
Hey mradway, Sorry I don't have that system now on which I was working, It was Anasoft HFSS 16 Evaluation copy downloaded from Anasoft website.
